# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Liyuan Wang/Desktop/Grad courses/EE 253/final_project/lab2_handout.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0.xci
# IP: The module: 'system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Liyuan Wang/Desktop/Grad courses/EE 253/final_project/lab2_handout.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/Liyuan Wang/Desktop/Grad courses/EE 253/final_project/lab2_handout.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0.xci
# IP: The module: 'system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Liyuan Wang/Desktop/Grad courses/EE 253/final_project/lab2_handout.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
