# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/liyuan/Desktop/lab2b/lab2_handout.srcs/sources_1/bd/system/ip/system_axi_gpio_2_3/system_axi_gpio_2_3.xci
# IP: The module: 'system_axi_gpio_2_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/liyuan/Desktop/lab2b/lab2_handout.srcs/sources_1/bd/system/ip/system_axi_gpio_2_3/system_axi_gpio_2_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/liyuan/Desktop/lab2b/lab2_handout.srcs/sources_1/bd/system/ip/system_axi_gpio_2_3/system_axi_gpio_2_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/liyuan/Desktop/lab2b/lab2_handout.srcs/sources_1/bd/system/ip/system_axi_gpio_2_3/system_axi_gpio_2_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/liyuan/Desktop/lab2b/lab2_handout.srcs/sources_1/bd/system/ip/system_axi_gpio_2_3/system_axi_gpio_2_3.xci
# IP: The module: 'system_axi_gpio_2_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/liyuan/Desktop/lab2b/lab2_handout.srcs/sources_1/bd/system/ip/system_axi_gpio_2_3/system_axi_gpio_2_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/liyuan/Desktop/lab2b/lab2_handout.srcs/sources_1/bd/system/ip/system_axi_gpio_2_3/system_axi_gpio_2_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/liyuan/Desktop/lab2b/lab2_handout.srcs/sources_1/bd/system/ip/system_axi_gpio_2_3/system_axi_gpio_2_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
