# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/liyuan/Desktop/lab2b/lab2_handout.srcs/sources_1/bd/system/ip/system_twist_0/system_twist_0.xci
# IP: The module: 'system_twist_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/liyuan/Desktop/lab2b/lab2_handout.srcs/sources_1/bd/system/ip/system_twist_0/system_twist_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_twist_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/liyuan/Desktop/lab2b/lab2_handout.srcs/sources_1/bd/system/ip/system_twist_0/system_twist_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_twist_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/liyuan/Desktop/lab2b/lab2_handout.srcs/sources_1/bd/system/ip/system_twist_0/system_twist_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_twist_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/liyuan/Desktop/lab2b/lab2_handout.srcs/sources_1/bd/system/ip/system_twist_0/system_twist_0.xci
# IP: The module: 'system_twist_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/liyuan/Desktop/lab2b/lab2_handout.srcs/sources_1/bd/system/ip/system_twist_0/system_twist_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_twist_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/liyuan/Desktop/lab2b/lab2_handout.srcs/sources_1/bd/system/ip/system_twist_0/system_twist_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_twist_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/liyuan/Desktop/lab2b/lab2_handout.srcs/sources_1/bd/system/ip/system_twist_0/system_twist_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_twist_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
